-
  name:  'Sitegeist.Taxonomy: Secondary Inspector'
  uriPattern: 'neos/taxonomy/secondary-inspector/{@action}'
  defaults:
    '@package': 'Sitegeist.Taxonomy'
    '@subpackage': ''
    '@controller': 'SecondaryInspector'
    '@format': 'json'
  httpMethods: ['GET']
